name: Production Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '12 12 * * *' 
    - cron: '24 18 * * *' 
    - cron: '52 2 * * *'
  workflow_dispatch:

jobs:
  cypress-execution:
    if: github.event_name == 'push' || github.event_name == 'schedule' || github.event_name == 'workflow_dispatch'
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: yarn install

      - name: Run Production Tests
        env:
          TERM: xterm
        run: yarn cypress run --spec "cypress/e2e/lps_producao_autmoatic_test/**/*.cy.js"
        continue-on-error: true

      - name: Run ERP Production Tests
        env:
          TERM: xterm
        run: yarn cypress run --spec "cypress/e2e/ERP/prod/cadastroPessoa.cy.js"
        continue-on-error: true

      - name: Generate Report
        if: always()
        run: yarn report:make

      - name: Upload Report Artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: report_production
          path: final-report
          if-no-files-found: error

      - name: Upload Media on Failure
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: cypress-media-failures
          path: |
            cypress/screenshots
            cypress/videos
          if-no-files-found: ignore